#######################
# info service v1     #
#######################

apiVersion: v1
kind: Service
metadata:
  name: info-v1
  labels:
    run: info-v1
spec:
  ports:
    - port: 80
      targetPort: 1080
  selector:
    run: info-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-v1
spec:
  selector:
    matchLabels:
      run: info-v1
  replicas: 2
  template:
    metadata:
      labels:
        run: info-v1
    spec:
      containers:
        - name: info-v1
          image: loriswit/watches-info-v1
          readinessProbe:
            httpGet:
              path: /health
              port: 1080
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 1080
          env:
            - name: HTTP_USER
              value: "$INFO_V1_HTTP_USER"
            - name: HTTP_PASS
              value: "$INFO_V1_HTTP_PASS"
            - name: DB_HOST
              value: "$INFO_V1_DB_HOST"
            - name: DB_PORT
              value: "$INFO_V1_DB_PORT"
            - name: DB_DBNAME
              value: "$INFO_V1_DB_DBNAME"
            - name: DB_USER
              value: "$INFO_V1_DB_USER"
            - name: DB_PASS
              value: "$INFO_V1_DB_PASS"
---

#######################
# image service v1    #
#######################

apiVersion: v1
kind: Service
metadata:
  name: image-v1
  labels:
    run: image-v1
spec:
  ports:
    - port: 80
      targetPort: 1080
  selector:
    run: image-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-v1
spec:
  selector:
    matchLabels:
      run: image-v1
  replicas: 2
  template:
    metadata:
      labels:
        run: image-v1
    spec:
      containers:
        - name: image-v1
          image: loriswit/watches-image-v1
          readinessProbe:
            httpGet:
              path: /health
              port: 1080
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 1080
---

#######################
# ingress             #
#######################

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths: # wildcards in paths are specific to GLBC
          - path: /info/v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: info-v1
                port:
                  number: 80
          - path: /image/v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: image-v1
                port:
                  number: 80
